/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMaomiAIInfraModelsErrorResponseFromDiscriminatorValue, createMaomiAIInfraModelsIdResponseFromDiscriminatorValue, serializeMaomiAIInfraModelsIdResponse, serializeMaomiAITeamSharedCommandsRootCreateTeamCommand, type MaomiAIInfraModelsErrorResponse, type MaomiAIInfraModelsIdResponse, type MaomiAITeamSharedCommandsRootCreateTeamCommand } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/team/create
 */
export interface CreateRequestBuilder extends BaseRequestBuilder<CreateRequestBuilder> {
    /**
     * 创建团队.
     * @param body 创建团队命令.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MaomiAIInfraModelsIdResponse>}
     * @throws {MaomiAIInfraModelsErrorResponse} error when the service returns a 400 status code
     * @throws {MaomiAIInfraModelsErrorResponse} error when the service returns a 401 status code
     * @throws {MaomiAIInfraModelsErrorResponse} error when the service returns a 403 status code
     * @throws {MaomiAIInfraModelsErrorResponse} error when the service returns a 409 status code
     * @throws {MaomiAIInfraModelsErrorResponse} error when the service returns a 500 status code
     */
     post(body: MaomiAITeamSharedCommandsRootCreateTeamCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MaomiAIInfraModelsIdResponse | undefined>;
    /**
     * 创建团队.
     * @param body 创建团队命令.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MaomiAITeamSharedCommandsRootCreateTeamCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CreateRequestBuilderUriTemplate = "{+baseurl}/api/team/create";
/**
 * Metadata for all the requests in the request builder.
 */
export const CreateRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: CreateRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMaomiAIInfraModelsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createMaomiAIInfraModelsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createMaomiAIInfraModelsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createMaomiAIInfraModelsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createMaomiAIInfraModelsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createMaomiAIInfraModelsIdResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMaomiAITeamSharedCommandsRootCreateTeamCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
