/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMaomiAIInfraModelsEmptyCommandResponseFromDiscriminatorValue, type MaomiAIInfraModelsEmptyCommandResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/team/{-id}/delete
 */
export interface DeleteRequestBuilder extends BaseRequestBuilder<DeleteRequestBuilder> {
    /**
     * 删除团队.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MaomiAIInfraModelsEmptyCommandResponse>}
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MaomiAIInfraModelsEmptyCommandResponse | undefined>;
    /**
     * 删除团队.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DeleteRequestBuilderUriTemplate = "{+baseurl}/api/team/{%2Did}/delete";
/**
 * Metadata for all the requests in the request builder.
 */
export const DeleteRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: DeleteRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createMaomiAIInfraModelsEmptyCommandResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
