/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AddRequestBuilderRequestsMetadata, type AddRequestBuilder } from './add/index.js';
// @ts-ignore
import { Default_aimodelRequestBuilderRequestsMetadata, type Default_aimodelRequestBuilder } from './default_aimodel/index.js';
// @ts-ignore
import { ProviderlistRequestBuilderRequestsMetadata, type ProviderlistRequestBuilder } from './providerlist/index.js';
// @ts-ignore
import { SetdefaultRequestBuilderRequestsMetadata, type SetdefaultRequestBuilder } from './setdefault/index.js';
// @ts-ignore
import { type TypeRequestBuilder, TypeRequestBuilderNavigationMetadata } from './type/index.js';
// @ts-ignore
import { type UpdateRequestBuilder, UpdateRequestBuilderRequestsMetadata } from './update/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/aimodel/{teamId}
 */
export interface WithTeamItemRequestBuilder extends BaseRequestBuilder<WithTeamItemRequestBuilder> {
    /**
     * The add property
     */
    get add(): AddRequestBuilder;
    /**
     * The default_aimodel property
     */
    get default_aimodel(): Default_aimodelRequestBuilder;
    /**
     * The providerlist property
     */
    get providerlist(): ProviderlistRequestBuilder;
    /**
     * The setdefault property
     */
    get setdefault(): SetdefaultRequestBuilder;
    /**
     * The type property
     */
    get type(): TypeRequestBuilder;
    /**
     * The update property
     */
    get update(): UpdateRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithTeamItemRequestBuilderUriTemplate = "{+baseurl}/api/aimodel/{teamId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithTeamItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithTeamItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    add: {
        requestsMetadata: AddRequestBuilderRequestsMetadata,
    },
    default_aimodel: {
        requestsMetadata: Default_aimodelRequestBuilderRequestsMetadata,
    },
    providerlist: {
        requestsMetadata: ProviderlistRequestBuilderRequestsMetadata,
    },
    setdefault: {
        requestsMetadata: SetdefaultRequestBuilderRequestsMetadata,
    },
    type: {
        navigationMetadata: TypeRequestBuilderNavigationMetadata,
    },
    update: {
        requestsMetadata: UpdateRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
