/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { Complate_upload_openapiRequestBuilderRequestsMetadata, type Complate_upload_openapiRequestBuilder } from './complate_upload_openapi/index.js';
// @ts-ignore
import { Delete_groupRequestBuilderRequestsMetadata, type Delete_groupRequestBuilder } from './delete_group/index.js';
// @ts-ignore
import { GrouplistRequestBuilderRequestsMetadata, type GrouplistRequestBuilder } from './grouplist/index.js';
// @ts-ignore
import { Import_mcpRequestBuilderRequestsMetadata, type Import_mcpRequestBuilder } from './import_mcp/index.js';
// @ts-ignore
import { PluginlistRequestBuilderRequestsMetadata, type PluginlistRequestBuilder } from './pluginlist/index.js';
// @ts-ignore
import { Pre_upload_openapiRequestBuilderRequestsMetadata, type Pre_upload_openapiRequestBuilder } from './pre_upload_openapi/index.js';
// @ts-ignore
import { type Update_groupRequestBuilder, Update_groupRequestBuilderRequestsMetadata } from './update_group/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/plugin/{teamId}
 */
export interface WithTeamItemRequestBuilder extends BaseRequestBuilder<WithTeamItemRequestBuilder> {
    /**
     * The complate_upload_openapi property
     */
    get complate_upload_openapi(): Complate_upload_openapiRequestBuilder;
    /**
     * The delete_group property
     */
    get delete_group(): Delete_groupRequestBuilder;
    /**
     * The grouplist property
     */
    get grouplist(): GrouplistRequestBuilder;
    /**
     * The import_mcp property
     */
    get import_mcp(): Import_mcpRequestBuilder;
    /**
     * The pluginlist property
     */
    get pluginlist(): PluginlistRequestBuilder;
    /**
     * The pre_upload_openapi property
     */
    get pre_upload_openapi(): Pre_upload_openapiRequestBuilder;
    /**
     * The update_group property
     */
    get update_group(): Update_groupRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithTeamItemRequestBuilderUriTemplate = "{+baseurl}/api/plugin/{teamId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithTeamItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithTeamItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    complate_upload_openapi: {
        requestsMetadata: Complate_upload_openapiRequestBuilderRequestsMetadata,
    },
    delete_group: {
        requestsMetadata: Delete_groupRequestBuilderRequestsMetadata,
    },
    grouplist: {
        requestsMetadata: GrouplistRequestBuilderRequestsMetadata,
    },
    import_mcp: {
        requestsMetadata: Import_mcpRequestBuilderRequestsMetadata,
    },
    pluginlist: {
        requestsMetadata: PluginlistRequestBuilderRequestsMetadata,
    },
    pre_upload_openapi: {
        requestsMetadata: Pre_upload_openapiRequestBuilderRequestsMetadata,
    },
    update_group: {
        requestsMetadata: Update_groupRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
