/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue, createMaomiAIInfraModelsEmptyCommandResponseFromDiscriminatorValue, serializeMaomiAIAiModelSharedCommandsSetDefaultAiModelCommand, serializeMaomiAIInfraModelsEmptyCommandResponse, type MaomiAIAiModelSharedCommandsSetDefaultAiModelCommand, type MaomiAIInfraModelsBusinessExceptionResponse, type MaomiAIInfraModelsEmptyCommandResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/aimodel/{teamId}/setdefault
 */
export interface SetdefaultRequestBuilder extends BaseRequestBuilder<SetdefaultRequestBuilder> {
    /**
     * 设置某个领域下默认的 ai 模型.
     * @param body 设置某个功能模型使用的 ai 模型.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MaomiAIInfraModelsEmptyCommandResponse>}
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 400 status code
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 401 status code
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 403 status code
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 409 status code
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 500 status code
     */
     post(body: MaomiAIAiModelSharedCommandsSetDefaultAiModelCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MaomiAIInfraModelsEmptyCommandResponse | undefined>;
    /**
     * 设置某个领域下默认的 ai 模型.
     * @param body 设置某个功能模型使用的 ai 模型.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MaomiAIAiModelSharedCommandsSetDefaultAiModelCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SetdefaultRequestBuilderUriTemplate = "{+baseurl}/api/aimodel/{teamId}/setdefault";
/**
 * Metadata for all the requests in the request builder.
 */
export const SetdefaultRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: SetdefaultRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createMaomiAIInfraModelsEmptyCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMaomiAIAiModelSharedCommandsSetDefaultAiModelCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
