/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMaomiAITeamSharedQueriesResponsesTeamDetailResponseFromDiscriminatorValue, type MaomiAITeamSharedQueriesResponsesTeamDetailResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/team/{-id}/teamdetail
 */
export interface TeamdetailRequestBuilder extends BaseRequestBuilder<TeamdetailRequestBuilder> {
    /**
     * 查询团队详细信息.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MaomiAITeamSharedQueriesResponsesTeamDetailResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MaomiAITeamSharedQueriesResponsesTeamDetailResponse | undefined>;
    /**
     * 查询团队详细信息.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TeamdetailRequestBuilderUriTemplate = "{+baseurl}/api/team/{%2Did}/teamdetail";
/**
 * Metadata for all the requests in the request builder.
 */
export const TeamdetailRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: TeamdetailRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createMaomiAITeamSharedQueriesResponsesTeamDetailResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
