/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessExceptionResponseFromDiscriminatorValue, createQueryPluginGroupListCommandResponseFromDiscriminatorValue, serializeQueryPluginGroupListCommand, serializeQueryPluginGroupListCommandResponse, type BusinessExceptionResponse, type QueryPluginGroupListCommand, type QueryPluginGroupListCommandResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/plugin/{teamId}/grouplist
 */
export interface GrouplistRequestBuilder extends BaseRequestBuilder<GrouplistRequestBuilder> {
    /**
     * 分组列表.
     * @param body 获取插件分组列表.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryPluginGroupListCommandResponse>}
     * @throws {BusinessExceptionResponse} error when the service returns a 400 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 401 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 403 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 409 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 500 status code
     */
     post(body: QueryPluginGroupListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryPluginGroupListCommandResponse | undefined>;
    /**
     * 分组列表.
     * @param body 获取插件分组列表.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryPluginGroupListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const GrouplistRequestBuilderUriTemplate = "{+baseurl}/api/plugin/{teamId}/grouplist";
/**
 * Metadata for all the requests in the request builder.
 */
export const GrouplistRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: GrouplistRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryPluginGroupListCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryPluginGroupListCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
