/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ModellistRequestBuilderRequestsMetadata, type ModellistRequestBuilder } from './modellist/index.js';
// @ts-ignore
import { ProviderlistRequestBuilderRequestsMetadata, type ProviderlistRequestBuilder } from './providerlist/index.js';
// @ts-ignore
import { type UpdateRequestBuilder, UpdateRequestBuilderRequestsMetadata } from './update/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/aimodel/{teamId}/admodel
 */
export interface AdmodelRequestBuilder extends BaseRequestBuilder<AdmodelRequestBuilder> {
    /**
     * The modellist property
     */
    get modellist(): ModellistRequestBuilder;
    /**
     * The providerlist property
     */
    get providerlist(): ProviderlistRequestBuilder;
    /**
     * The update property
     */
    get update(): UpdateRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AdmodelRequestBuilderUriTemplate = "{+baseurl}/api/aimodel/{teamId}/admodel";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AdmodelRequestBuilderNavigationMetadata: Record<Exclude<keyof AdmodelRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    modellist: {
        requestsMetadata: ModellistRequestBuilderRequestsMetadata,
    },
    providerlist: {
        requestsMetadata: ProviderlistRequestBuilderRequestsMetadata,
    },
    update: {
        requestsMetadata: UpdateRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
