/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithTeamItemRequestBuilder, WithTeamItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki
 */
export interface WikiRequestBuilder extends BaseRequestBuilder<WikiRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.wiki.item collection
     * @param teamId Unique identifier of the item
     * @returns {WithTeamItemRequestBuilder}
     */
     byTeamId(teamId: Guid) : WithTeamItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WikiRequestBuilderUriTemplate = "{+baseurl}/api/wiki";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WikiRequestBuilderNavigationMetadata: Record<Exclude<keyof WikiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTeamId: {
        navigationMetadata: WithTeamItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["teamId"],
    },
};
/* tslint:enable */
/* eslint-enable */
