/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessExceptionResponseFromDiscriminatorValue, createQueryWikiSimpleInfoResponseFromDiscriminatorValue, serializeQueryWikiSimpleInfoCommand, serializeQueryWikiSimpleInfoResponse, type BusinessExceptionResponse, type QueryWikiSimpleInfoCommand, type QueryWikiSimpleInfoResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/{temaId}/simple_info
 */
export interface Simple_infoRequestBuilder extends BaseRequestBuilder<Simple_infoRequestBuilder> {
    /**
     * 查询知识库的简单信息.
     * @param body 获取知识库简单信息.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryWikiSimpleInfoResponse>}
     * @throws {BusinessExceptionResponse} error when the service returns a 400 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 401 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 403 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 409 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 500 status code
     */
     post(body: QueryWikiSimpleInfoCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryWikiSimpleInfoResponse | undefined>;
    /**
     * 查询知识库的简单信息.
     * @param body 获取知识库简单信息.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryWikiSimpleInfoCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Simple_infoRequestBuilderUriTemplate = "{+baseurl}/api/wiki/{temaId}/simple_info";
/**
 * Metadata for all the requests in the request builder.
 */
export const Simple_infoRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Simple_infoRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryWikiSimpleInfoResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryWikiSimpleInfoCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
