/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMaomiAIStoreQueriesResponseCheckFileExistCommandResponseFromDiscriminatorValue, serializeMaomiAIStoreQueriesCheckFileExistCommand, serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse, type MaomiAIStoreQueriesCheckFileExistCommand, type MaomiAIStoreQueriesResponseCheckFileExistCommandResponse } from '../../../models/index.js';
// @ts-ignore
import { type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/store/check_exist
 */
export interface Check_existRequestBuilder extends BaseRequestBuilder<Check_existRequestBuilder> {
    /**
     * 检查文件是否存在.
     * @param body 检查文件是否存在
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse>}
     * @throws {MaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error} error when the service returns a 400 status code
     * @throws {MaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error} error when the service returns a 401 status code
     * @throws {MaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error} error when the service returns a 403 status code
     * @throws {MaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error} error when the service returns a 409 status code
     * @throws {MaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error} error when the service returns a 500 status code
     */
     post(body: MaomiAIStoreQueriesCheckFileExistCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse | undefined>;
    /**
     * 检查文件是否存在.
     * @param body 检查文件是否存在
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MaomiAIStoreQueriesCheckFileExistCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_errors}
 */
// @ts-ignore
export function createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_extensions}
 */
// @ts-ignore
export function createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_extensionsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_extensions;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error}
 */
// @ts-ignore
export function createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_errors}
 */
// @ts-ignore
export function createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_extensions}
 */
// @ts-ignore
export function createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_extensionsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_extensions;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error}
 */
// @ts-ignore
export function createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse401ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_errors}
 */
// @ts-ignore
export function createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_extensions}
 */
// @ts-ignore
export function createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_extensionsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_extensions;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error}
 */
// @ts-ignore
export function createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse403ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_errors}
 */
// @ts-ignore
export function createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_extensions}
 */
// @ts-ignore
export function createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_extensionsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_extensions;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error}
 */
// @ts-ignore
export function createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse409ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_errors}
 */
// @ts-ignore
export function createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_extensions}
 */
// @ts-ignore
export function createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_extensionsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_extensions;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error}
 */
// @ts-ignore
export function createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse500ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error(maomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error.code = n.getNumberValue(); },
        "detail": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error.detail = n.getStringValue(); },
        "errors": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error.errors = n.getObjectValue<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_errors>(createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_errorsFromDiscriminatorValue); },
        "extensions": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error.extensions = n.getObjectValue<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_extensions>(createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_extensionsFromDiscriminatorValue); },
        "requestId": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error.requestId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_errors(maomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_errors: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_extensions(maomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_extensions: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_extensions> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error(maomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error.code = n.getNumberValue(); },
        "detail": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error.detail = n.getStringValue(); },
        "errors": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error.errors = n.getObjectValue<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_errors>(createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_errorsFromDiscriminatorValue); },
        "extensions": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error.extensions = n.getObjectValue<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_extensions>(createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_extensionsFromDiscriminatorValue); },
        "requestId": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error.requestId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_errors(maomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_errors: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_extensions(maomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_extensions: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_extensions> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error(maomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error.code = n.getNumberValue(); },
        "detail": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error.detail = n.getStringValue(); },
        "errors": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error.errors = n.getObjectValue<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_errors>(createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_errorsFromDiscriminatorValue); },
        "extensions": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error.extensions = n.getObjectValue<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_extensions>(createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_extensionsFromDiscriminatorValue); },
        "requestId": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error.requestId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_errors(maomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_errors: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_extensions(maomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_extensions: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_extensions> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error(maomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error.code = n.getNumberValue(); },
        "detail": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error.detail = n.getStringValue(); },
        "errors": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error.errors = n.getObjectValue<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_errors>(createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_errorsFromDiscriminatorValue); },
        "extensions": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error.extensions = n.getObjectValue<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_extensions>(createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_extensionsFromDiscriminatorValue); },
        "requestId": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error.requestId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_errors(maomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_errors: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_extensions(maomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_extensions: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_extensions> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error(maomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error.code = n.getNumberValue(); },
        "detail": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error.detail = n.getStringValue(); },
        "errors": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error.errors = n.getObjectValue<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_errors>(createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_errorsFromDiscriminatorValue); },
        "extensions": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error.extensions = n.getObjectValue<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_extensions>(createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_extensionsFromDiscriminatorValue); },
        "requestId": n => { maomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error.requestId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_errors(maomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_errors: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_extensions(maomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_extensions: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_extensions> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * 错误响应模型.
 */
export interface MaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error extends ApiError, Parsable {
    /**
     * 错误码.
     */
    code?: number | null;
    /**
     * 错误消息.
     */
    detail?: string | null;
    /**
     * 具体错误列表.
     */
    errors?: MaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_errors | null;
    /**
     * 扩展.
     */
    extensions?: MaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_extensions | null;
    /**
     * 请求上下文 ID.
     */
    requestId?: string | null;
}
/**
 * 具体错误列表.
 */
export interface MaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_errors extends Parsable {
}
/**
 * 扩展.
 */
export interface MaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_extensions extends Parsable {
}
/**
 * 错误响应模型.
 */
export interface MaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error extends ApiError, Parsable {
    /**
     * 错误码.
     */
    code?: number | null;
    /**
     * 错误消息.
     */
    detail?: string | null;
    /**
     * 具体错误列表.
     */
    errors?: MaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_errors | null;
    /**
     * 扩展.
     */
    extensions?: MaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_extensions | null;
    /**
     * 请求上下文 ID.
     */
    requestId?: string | null;
}
/**
 * 具体错误列表.
 */
export interface MaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_errors extends Parsable {
}
/**
 * 扩展.
 */
export interface MaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_extensions extends Parsable {
}
/**
 * 错误响应模型.
 */
export interface MaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error extends ApiError, Parsable {
    /**
     * 错误码.
     */
    code?: number | null;
    /**
     * 错误消息.
     */
    detail?: string | null;
    /**
     * 具体错误列表.
     */
    errors?: MaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_errors | null;
    /**
     * 扩展.
     */
    extensions?: MaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_extensions | null;
    /**
     * 请求上下文 ID.
     */
    requestId?: string | null;
}
/**
 * 具体错误列表.
 */
export interface MaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_errors extends Parsable {
}
/**
 * 扩展.
 */
export interface MaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_extensions extends Parsable {
}
/**
 * 错误响应模型.
 */
export interface MaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error extends ApiError, Parsable {
    /**
     * 错误码.
     */
    code?: number | null;
    /**
     * 错误消息.
     */
    detail?: string | null;
    /**
     * 具体错误列表.
     */
    errors?: MaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_errors | null;
    /**
     * 扩展.
     */
    extensions?: MaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_extensions | null;
    /**
     * 请求上下文 ID.
     */
    requestId?: string | null;
}
/**
 * 具体错误列表.
 */
export interface MaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_errors extends Parsable {
}
/**
 * 扩展.
 */
export interface MaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_extensions extends Parsable {
}
/**
 * 错误响应模型.
 */
export interface MaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error extends ApiError, Parsable {
    /**
     * 错误码.
     */
    code?: number | null;
    /**
     * 错误消息.
     */
    detail?: string | null;
    /**
     * 具体错误列表.
     */
    errors?: MaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_errors | null;
    /**
     * 扩展.
     */
    extensions?: MaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_extensions | null;
    /**
     * 请求上下文 ID.
     */
    requestId?: string | null;
}
/**
 * 具体错误列表.
 */
export interface MaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_errors extends Parsable {
}
/**
 * 扩展.
 */
export interface MaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_extensions extends Parsable {
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error(writer: SerializationWriter, maomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error> | undefined | null = {}) : void {
    if (maomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error) {
        writer.writeNumberValue("code", maomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error.code);
        writer.writeStringValue("detail", maomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error.detail);
        writer.writeObjectValue<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_errors>("errors", maomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error.errors, serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_errors);
        writer.writeObjectValue<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_extensions>("extensions", maomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error.extensions, serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_extensions);
        writer.writeStringValue("requestId", maomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error.requestId);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_errors(writer: SerializationWriter, maomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_errors: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_errors> | undefined | null = {}) : void {
    if (maomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_errors) {
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_extensions(writer: SerializationWriter, maomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_extensions: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_extensions> | undefined | null = {}) : void {
    if (maomiAIStoreQueriesResponseCheckFileExistCommandResponse400Error_extensions) {
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error(writer: SerializationWriter, maomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error> | undefined | null = {}) : void {
    if (maomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error) {
        writer.writeNumberValue("code", maomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error.code);
        writer.writeStringValue("detail", maomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error.detail);
        writer.writeObjectValue<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_errors>("errors", maomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error.errors, serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_errors);
        writer.writeObjectValue<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_extensions>("extensions", maomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error.extensions, serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_extensions);
        writer.writeStringValue("requestId", maomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error.requestId);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_errors(writer: SerializationWriter, maomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_errors: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_errors> | undefined | null = {}) : void {
    if (maomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_errors) {
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_extensions(writer: SerializationWriter, maomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_extensions: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_extensions> | undefined | null = {}) : void {
    if (maomiAIStoreQueriesResponseCheckFileExistCommandResponse401Error_extensions) {
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error(writer: SerializationWriter, maomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error> | undefined | null = {}) : void {
    if (maomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error) {
        writer.writeNumberValue("code", maomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error.code);
        writer.writeStringValue("detail", maomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error.detail);
        writer.writeObjectValue<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_errors>("errors", maomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error.errors, serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_errors);
        writer.writeObjectValue<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_extensions>("extensions", maomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error.extensions, serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_extensions);
        writer.writeStringValue("requestId", maomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error.requestId);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_errors(writer: SerializationWriter, maomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_errors: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_errors> | undefined | null = {}) : void {
    if (maomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_errors) {
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_extensions(writer: SerializationWriter, maomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_extensions: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_extensions> | undefined | null = {}) : void {
    if (maomiAIStoreQueriesResponseCheckFileExistCommandResponse403Error_extensions) {
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error(writer: SerializationWriter, maomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error> | undefined | null = {}) : void {
    if (maomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error) {
        writer.writeNumberValue("code", maomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error.code);
        writer.writeStringValue("detail", maomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error.detail);
        writer.writeObjectValue<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_errors>("errors", maomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error.errors, serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_errors);
        writer.writeObjectValue<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_extensions>("extensions", maomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error.extensions, serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_extensions);
        writer.writeStringValue("requestId", maomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error.requestId);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_errors(writer: SerializationWriter, maomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_errors: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_errors> | undefined | null = {}) : void {
    if (maomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_errors) {
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_extensions(writer: SerializationWriter, maomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_extensions: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_extensions> | undefined | null = {}) : void {
    if (maomiAIStoreQueriesResponseCheckFileExistCommandResponse409Error_extensions) {
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error(writer: SerializationWriter, maomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error> | undefined | null = {}) : void {
    if (maomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error) {
        writer.writeNumberValue("code", maomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error.code);
        writer.writeStringValue("detail", maomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error.detail);
        writer.writeObjectValue<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_errors>("errors", maomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error.errors, serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_errors);
        writer.writeObjectValue<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_extensions>("extensions", maomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error.extensions, serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_extensions);
        writer.writeStringValue("requestId", maomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error.requestId);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_errors(writer: SerializationWriter, maomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_errors: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_errors> | undefined | null = {}) : void {
    if (maomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_errors) {
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_extensions(writer: SerializationWriter, maomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_extensions: Partial<MaomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_extensions> | undefined | null = {}) : void {
    if (maomiAIStoreQueriesResponseCheckFileExistCommandResponse500Error_extensions) {
    }
}
/**
 * Uri template for the request builder.
 */
export const Check_existRequestBuilderUriTemplate = "{+baseurl}/api/store/check_exist";
/**
 * Metadata for all the requests in the request builder.
 */
export const Check_existRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Check_existRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse401ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse403ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse409ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createMaomiAIStoreQueriesResponseCheckFileExistCommandResponse500ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createMaomiAIStoreQueriesResponseCheckFileExistCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMaomiAIStoreQueriesCheckFileExistCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
