/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMaomiAIInfraModelsSimpleOfBooleanFromDiscriminatorValue, serializeMaomiAIInfraModelsSimpleOfBoolean, serializeMaomiAIUserSharedQueriesQueryRepeatedUserNameCommand, type MaomiAIInfraModelsSimpleOfBoolean, type MaomiAIUserSharedQueriesQueryRepeatedUserNameCommand } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/user/checkname
 */
export interface ChecknameRequestBuilder extends BaseRequestBuilder<ChecknameRequestBuilder> {
    /**
     * 查询用户名是否重复.
     * @param body 检查用户名是否重复.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MaomiAIInfraModelsSimpleOfBoolean>}
     */
     post(body: MaomiAIUserSharedQueriesQueryRepeatedUserNameCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MaomiAIInfraModelsSimpleOfBoolean | undefined>;
    /**
     * 查询用户名是否重复.
     * @param body 检查用户名是否重复.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MaomiAIUserSharedQueriesQueryRepeatedUserNameCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ChecknameRequestBuilderUriTemplate = "{+baseurl}/api/user/checkname";
/**
 * Metadata for all the requests in the request builder.
 */
export const ChecknameRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ChecknameRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createMaomiAIInfraModelsSimpleOfBooleanFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMaomiAIUserSharedQueriesQueryRepeatedUserNameCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
