/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessExceptionResponseFromDiscriminatorValue, createSimpleOfBooleanFromDiscriminatorValue, serializeQueryRepeatedUserNameCommand, serializeSimpleOfBoolean, type BusinessExceptionResponse, type QueryRepeatedUserNameCommand, type SimpleOfBoolean } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/user/checkname
 */
export interface ChecknameRequestBuilder extends BaseRequestBuilder<ChecknameRequestBuilder> {
    /**
     * 查询用户名是否重复.
     * @param body 检查用户名是否重复.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SimpleOfBoolean>}
     * @throws {BusinessExceptionResponse} error when the service returns a 400 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 401 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 403 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 409 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 500 status code
     */
     post(body: QueryRepeatedUserNameCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SimpleOfBoolean | undefined>;
    /**
     * 查询用户名是否重复.
     * @param body 检查用户名是否重复.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryRepeatedUserNameCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ChecknameRequestBuilderUriTemplate = "{+baseurl}/api/user/checkname";
/**
 * Metadata for all the requests in the request builder.
 */
export const ChecknameRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ChecknameRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSimpleOfBooleanFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryRepeatedUserNameCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
