/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { DefaultconfigurationRequestBuilderRequestsMetadata, type DefaultconfigurationRequestBuilder } from './defaultconfiguration/index.js';
// @ts-ignore
import { Support_providerRequestBuilderRequestsMetadata, type Support_providerRequestBuilder } from './support_provider/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/aimodel/aimodel
 */
export interface AimodelRequestBuilder extends BaseRequestBuilder<AimodelRequestBuilder> {
    /**
     * The defaultconfiguration property
     */
    get defaultconfiguration(): DefaultconfigurationRequestBuilder;
    /**
     * The support_provider property
     */
    get support_provider(): Support_providerRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AimodelRequestBuilderUriTemplate = "{+baseurl}/api/aimodel/aimodel";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AimodelRequestBuilderNavigationMetadata: Record<Exclude<keyof AimodelRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    defaultconfiguration: {
        requestsMetadata: DefaultconfigurationRequestBuilderRequestsMetadata,
    },
    support_provider: {
        requestsMetadata: Support_providerRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
