/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ConfigRequestBuilderRequestsMetadata, type ConfigRequestBuilder } from './config/index.js';
// @ts-ignore
import { CreateRequestBuilderRequestsMetadata, type CreateRequestBuilder } from './create/index.js';
// @ts-ignore
import { DeleteRequestBuilderRequestsMetadata, type DeleteRequestBuilder } from './delete/index.js';
// @ts-ignore
import { DetailRequestBuilderRequestsMetadata, type DetailRequestBuilder } from './detail/index.js';
// @ts-ignore
import { DocumentRequestBuilderNavigationMetadata, type DocumentRequestBuilder } from './document/index.js';
// @ts-ignore
import { InfoRequestBuilderRequestsMetadata, type InfoRequestBuilder } from './info/index.js';
// @ts-ignore
import { SettingsRequestBuilderNavigationMetadata, type SettingsRequestBuilder } from './settings/index.js';
// @ts-ignore
import { Simple_infoRequestBuilderRequestsMetadata, type Simple_infoRequestBuilder } from './simple_info/index.js';
// @ts-ignore
import { type WikisRequestBuilder, WikisRequestBuilderRequestsMetadata } from './wikis/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/{temaId}
 */
export interface WithTemaItemRequestBuilder extends BaseRequestBuilder<WithTemaItemRequestBuilder> {
    /**
     * The config property
     */
    get config(): ConfigRequestBuilder;
    /**
     * The create property
     */
    get create(): CreateRequestBuilder;
    /**
     * The deletePath property
     */
    get deletePath(): DeleteRequestBuilder;
    /**
     * The detail property
     */
    get detail(): DetailRequestBuilder;
    /**
     * The document property
     */
    get document(): DocumentRequestBuilder;
    /**
     * The info property
     */
    get info(): InfoRequestBuilder;
    /**
     * The settings property
     */
    get settings(): SettingsRequestBuilder;
    /**
     * The simple_info property
     */
    get simple_info(): Simple_infoRequestBuilder;
    /**
     * The wikis property
     */
    get wikis(): WikisRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithTemaItemRequestBuilderUriTemplate = "{+baseurl}/api/wiki/{temaId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithTemaItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithTemaItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    config: {
        requestsMetadata: ConfigRequestBuilderRequestsMetadata,
    },
    create: {
        requestsMetadata: CreateRequestBuilderRequestsMetadata,
    },
    deletePath: {
        requestsMetadata: DeleteRequestBuilderRequestsMetadata,
    },
    detail: {
        requestsMetadata: DetailRequestBuilderRequestsMetadata,
    },
    document: {
        navigationMetadata: DocumentRequestBuilderNavigationMetadata,
    },
    info: {
        requestsMetadata: InfoRequestBuilderRequestsMetadata,
    },
    settings: {
        navigationMetadata: SettingsRequestBuilderNavigationMetadata,
    },
    simple_info: {
        requestsMetadata: Simple_infoRequestBuilderRequestsMetadata,
    },
    wikis: {
        requestsMetadata: WikisRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
