/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CreateRequestBuilderRequestsMetadata, type CreateRequestBuilder } from './create/index.js';
// @ts-ignore
import { type WithWikiItemRequestBuilder, WithWikiItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type WikisRequestBuilder, WikisRequestBuilderRequestsMetadata } from './wikis/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/{teamId}
 */
export interface WithTeamItemRequestBuilder extends BaseRequestBuilder<WithTeamItemRequestBuilder> {
    /**
     * The create property
     */
    get create(): CreateRequestBuilder;
    /**
     * The wikis property
     */
    get wikis(): WikisRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.wiki.item.item collection
     * @param wikiId Unique identifier of the item
     * @returns {WithWikiItemRequestBuilder}
     */
     byWikiId(wikiId: Guid) : WithWikiItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithTeamItemRequestBuilderUriTemplate = "{+baseurl}/api/wiki/{teamId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithTeamItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithTeamItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byWikiId: {
        navigationMetadata: WithWikiItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["wikiId"],
    },
    create: {
        requestsMetadata: CreateRequestBuilderRequestsMetadata,
    },
    wikis: {
        requestsMetadata: WikisRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
