/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type UploadavatarRequestBuilder, UploadavatarRequestBuilderRequestsMetadata } from './uploadavatar/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/team/config
 */
export interface ConfigRequestBuilder extends BaseRequestBuilder<ConfigRequestBuilder> {
    /**
     * The uploadavatar property
     */
    get uploadavatar(): UploadavatarRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ConfigRequestBuilderUriTemplate = "{+baseurl}/api/team/config";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ConfigRequestBuilderNavigationMetadata: Record<Exclude<keyof ConfigRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    uploadavatar: {
        requestsMetadata: UploadavatarRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
