/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMaomiAIAiModelSharedQueriesResponesQueryAiModelListCommandResponseFromDiscriminatorValue, createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue, serializeMaomiAIAiModelSharedQueriesQueryAiModelListCommand, serializeMaomiAIAiModelSharedQueriesResponesQueryAiModelListCommandResponse, type MaomiAIAiModelSharedQueriesQueryAiModelListCommand, type MaomiAIAiModelSharedQueriesResponesQueryAiModelListCommandResponse, type MaomiAIInfraModelsBusinessExceptionResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/aimodel/{teamId}/modellist
 */
export interface ModellistRequestBuilder extends BaseRequestBuilder<ModellistRequestBuilder> {
    /**
     * 查询团队在某个供应商下的模型列表.
     * @param body 查询供应商下已配置的 ai 模型列表.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MaomiAIAiModelSharedQueriesResponesQueryAiModelListCommandResponse>}
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 400 status code
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 401 status code
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 403 status code
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 409 status code
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 500 status code
     */
     post(body: MaomiAIAiModelSharedQueriesQueryAiModelListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MaomiAIAiModelSharedQueriesResponesQueryAiModelListCommandResponse | undefined>;
    /**
     * 查询团队在某个供应商下的模型列表.
     * @param body 查询供应商下已配置的 ai 模型列表.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MaomiAIAiModelSharedQueriesQueryAiModelListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ModellistRequestBuilderUriTemplate = "{+baseurl}/api/aimodel/{teamId}/modellist";
/**
 * Metadata for all the requests in the request builder.
 */
export const ModellistRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ModellistRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createMaomiAIAiModelSharedQueriesResponesQueryAiModelListCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMaomiAIAiModelSharedQueriesQueryAiModelListCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
