/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessExceptionResponseFromDiscriminatorValue, createQueryWikiFileListItemFromDiscriminatorValue, serializeQueryWikiFileCommand, serializeQueryWikiFileListItem, type BusinessExceptionResponse, type QueryWikiFileCommand, type QueryWikiFileListItem } from '../../../../../models/index.js';
// @ts-ignore
import { SearchRequestBuilderRequestsMetadata, type SearchRequestBuilder } from './search/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/{teamId}/{wikiId}/document
 */
export interface DocumentRequestBuilder extends BaseRequestBuilder<DocumentRequestBuilder> {
    /**
     * The search property
     */
    get search(): SearchRequestBuilder;
    /**
     * 获取知识库文件.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryWikiFileListItem>}
     * @throws {BusinessExceptionResponse} error when the service returns a 400 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 401 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 403 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 409 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 500 status code
     */
     post(body: QueryWikiFileCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryWikiFileListItem | undefined>;
    /**
     * 获取知识库文件.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryWikiFileCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DocumentRequestBuilderUriTemplate = "{+baseurl}/api/wiki/{teamId}/{wikiId}/document";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DocumentRequestBuilderNavigationMetadata: Record<Exclude<keyof DocumentRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    search: {
        requestsMetadata: SearchRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const DocumentRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: DocumentRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryWikiFileListItemFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryWikiFileCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
