/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessExceptionResponseFromDiscriminatorValue, createIdResponseFromDiscriminatorValue, serializeComplateOpenApiFileCommand, serializeIdResponse, type BusinessExceptionResponse, type ComplateOpenApiFileCommand, type IdResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/plugin/{teamId}/complate_upload_openapi
 */
export interface Complate_upload_openapiRequestBuilder extends BaseRequestBuilder<Complate_upload_openapiRequestBuilder> {
    /**
     * 完成 openapi 文件上传.
     * @param body 预上传 openapi 文件，支持 json、yaml.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<IdResponse>}
     * @throws {BusinessExceptionResponse} error when the service returns a 400 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 401 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 403 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 409 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 500 status code
     */
     post(body: ComplateOpenApiFileCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<IdResponse | undefined>;
    /**
     * 完成 openapi 文件上传.
     * @param body 预上传 openapi 文件，支持 json、yaml.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ComplateOpenApiFileCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Complate_upload_openapiRequestBuilderUriTemplate = "{+baseurl}/api/plugin/{teamId}/complate_upload_openapi";
/**
 * Metadata for all the requests in the request builder.
 */
export const Complate_upload_openapiRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Complate_upload_openapiRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createIdResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeComplateOpenApiFileCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
