/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue, createMaomiAIInfraModelsEmptyCommandResponseFromDiscriminatorValue, serializeMaomiAIDocumentSharedQueriesDocumentsCancalWikiDocumentTaskCommand, serializeMaomiAIInfraModelsEmptyCommandResponse, type MaomiAIDocumentSharedQueriesDocumentsCancalWikiDocumentTaskCommand, type MaomiAIInfraModelsBusinessExceptionResponse, type MaomiAIInfraModelsEmptyCommandResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/{team-id}/canal_document_tasks
 */
export interface Canal_document_tasksRequestBuilder extends BaseRequestBuilder<Canal_document_tasksRequestBuilder> {
    /**
     * 获取文档任务列表.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MaomiAIInfraModelsEmptyCommandResponse>}
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 400 status code
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 401 status code
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 403 status code
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 409 status code
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 500 status code
     */
     post(body: MaomiAIDocumentSharedQueriesDocumentsCancalWikiDocumentTaskCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MaomiAIInfraModelsEmptyCommandResponse | undefined>;
    /**
     * 获取文档任务列表.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MaomiAIDocumentSharedQueriesDocumentsCancalWikiDocumentTaskCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Canal_document_tasksRequestBuilderUriTemplate = "{+baseurl}/api/wiki/{team%2Did}/canal_document_tasks";
/**
 * Metadata for all the requests in the request builder.
 */
export const Canal_document_tasksRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Canal_document_tasksRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createMaomiAIInfraModelsEmptyCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMaomiAIDocumentSharedQueriesDocumentsCancalWikiDocumentTaskCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
