/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithTeamItemRequestBuilder, WithTeamItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { ListRequestBuilderRequestsMetadata, type ListRequestBuilder } from './list/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/prompt
 */
export interface PromptRequestBuilder extends BaseRequestBuilder<PromptRequestBuilder> {
    /**
     * The list property
     */
    get list(): ListRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.prompt.item collection
     * @param teamId Unique identifier of the item
     * @returns {WithTeamItemRequestBuilder}
     */
     byTeamId(teamId: Guid) : WithTeamItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PromptRequestBuilderUriTemplate = "{+baseurl}/api/prompt";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PromptRequestBuilderNavigationMetadata: Record<Exclude<keyof PromptRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTeamId: {
        navigationMetadata: WithTeamItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["teamId"],
    },
    list: {
        requestsMetadata: ListRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
