/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessExceptionResponseFromDiscriminatorValue, createSimpleOfStringFromDiscriminatorValue, serializeSimpleOfString, type BusinessExceptionResponse, type SimpleOfString } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/public/encryption
 */
export interface EncryptionRequestBuilder extends BaseRequestBuilder<EncryptionRequestBuilder> {
    /**
     * 加密信息.
     * @param body 简单类型.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SimpleOfString>}
     * @throws {BusinessExceptionResponse} error when the service returns a 400 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 401 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 403 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 409 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 500 status code
     */
     post(body: SimpleOfString, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SimpleOfString | undefined>;
    /**
     * 加密信息.
     * @param body 简单类型.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SimpleOfString, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const EncryptionRequestBuilderUriTemplate = "{+baseurl}/api/public/encryption";
/**
 * Metadata for all the requests in the request builder.
 */
export const EncryptionRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: EncryptionRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSimpleOfStringFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSimpleOfString,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
