/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMaomiAIInfraModelsSimpleOfStringFromDiscriminatorValue, serializeMaomiAIInfraModelsSimpleOfString, type MaomiAIInfraModelsSimpleOfString } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/public/encryption
 */
export interface EncryptionRequestBuilder extends BaseRequestBuilder<EncryptionRequestBuilder> {
    /**
     * 加密信息.
     * @param body 简单类型.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MaomiAIInfraModelsSimpleOfString>}
     */
     post(body: MaomiAIInfraModelsSimpleOfString, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MaomiAIInfraModelsSimpleOfString | undefined>;
    /**
     * 加密信息.
     * @param body 简单类型.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MaomiAIInfraModelsSimpleOfString, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const EncryptionRequestBuilderUriTemplate = "{+baseurl}/api/public/encryption";
/**
 * Metadata for all the requests in the request builder.
 */
export const EncryptionRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: EncryptionRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createMaomiAIInfraModelsSimpleOfStringFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMaomiAIInfraModelsSimpleOfString,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
