/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMaomiAIInfraModelsEmptyCommandResponseFromDiscriminatorValue, createMaomiAIInfraModelsErrorResponseFromDiscriminatorValue, serializeMaomiAIInfraModelsEmptyCommandResponse, serializeMaomiAITeamSharedCommandsRootUploadTeamAvatarCommand, type MaomiAIInfraModelsEmptyCommandResponse, type MaomiAIInfraModelsErrorResponse, type MaomiAITeamSharedCommandsRootUploadTeamAvatarCommand } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/team/config/uploadavatar
 */
export interface UploadavatarRequestBuilder extends BaseRequestBuilder<UploadavatarRequestBuilder> {
    /**
     * 上传头像.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MaomiAIInfraModelsEmptyCommandResponse>}
     * @throws {MaomiAIInfraModelsErrorResponse} error when the service returns a 400 status code
     * @throws {MaomiAIInfraModelsErrorResponse} error when the service returns a 401 status code
     * @throws {MaomiAIInfraModelsErrorResponse} error when the service returns a 403 status code
     * @throws {MaomiAIInfraModelsErrorResponse} error when the service returns a 409 status code
     * @throws {MaomiAIInfraModelsErrorResponse} error when the service returns a 500 status code
     */
     post(body: MaomiAITeamSharedCommandsRootUploadTeamAvatarCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MaomiAIInfraModelsEmptyCommandResponse | undefined>;
    /**
     * 上传头像.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MaomiAITeamSharedCommandsRootUploadTeamAvatarCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const UploadavatarRequestBuilderUriTemplate = "{+baseurl}/api/team/config/uploadavatar";
/**
 * Metadata for all the requests in the request builder.
 */
export const UploadavatarRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: UploadavatarRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMaomiAIInfraModelsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createMaomiAIInfraModelsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createMaomiAIInfraModelsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createMaomiAIInfraModelsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createMaomiAIInfraModelsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createMaomiAIInfraModelsEmptyCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMaomiAITeamSharedCommandsRootUploadTeamAvatarCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
