/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AdminlistRequestBuilderRequestsMetadata, type AdminlistRequestBuilder } from './adminlist/index.js';
// @ts-ignore
import { DeleteRequestBuilderRequestsMetadata, type DeleteRequestBuilder } from './delete/index.js';
// @ts-ignore
import { MemberlistRequestBuilderRequestsMetadata, type MemberlistRequestBuilder } from './memberlist/index.js';
// @ts-ignore
import { TeamdetailRequestBuilderRequestsMetadata, type TeamdetailRequestBuilder } from './teamdetail/index.js';
// @ts-ignore
import { TeamitemRequestBuilderRequestsMetadata, type TeamitemRequestBuilder } from './teamitem/index.js';
// @ts-ignore
import { type UpdateRequestBuilder, UpdateRequestBuilderRequestsMetadata } from './update/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/team/{-id}
 */
export interface ItemRequestBuilder extends BaseRequestBuilder<ItemRequestBuilder> {
    /**
     * The adminlist property
     */
    get adminlist(): AdminlistRequestBuilder;
    /**
     * The deletePath property
     */
    get deletePath(): DeleteRequestBuilder;
    /**
     * The memberlist property
     */
    get memberlist(): MemberlistRequestBuilder;
    /**
     * The teamdetail property
     */
    get teamdetail(): TeamdetailRequestBuilder;
    /**
     * The teamitem property
     */
    get teamitem(): TeamitemRequestBuilder;
    /**
     * The update property
     */
    get update(): UpdateRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ItemRequestBuilderUriTemplate = "{+baseurl}/api/team/{%2Did}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ItemRequestBuilderNavigationMetadata: Record<Exclude<keyof ItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    adminlist: {
        requestsMetadata: AdminlistRequestBuilderRequestsMetadata,
    },
    deletePath: {
        requestsMetadata: DeleteRequestBuilderRequestsMetadata,
    },
    memberlist: {
        requestsMetadata: MemberlistRequestBuilderRequestsMetadata,
    },
    teamdetail: {
        requestsMetadata: TeamdetailRequestBuilderRequestsMetadata,
    },
    teamitem: {
        requestsMetadata: TeamitemRequestBuilderRequestsMetadata,
    },
    update: {
        requestsMetadata: UpdateRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
