/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AdminlistRequestBuilderRequestsMetadata, type AdminlistRequestBuilder } from './adminlist/index.js';
// @ts-ignore
import { ConfigRequestBuilderNavigationMetadata, type ConfigRequestBuilder } from './config/index.js';
// @ts-ignore
import { CreateRequestBuilderRequestsMetadata, type CreateRequestBuilder } from './create/index.js';
// @ts-ignore
import { DeleteRequestBuilderRequestsMetadata, type DeleteRequestBuilder } from './delete/index.js';
// @ts-ignore
import { InfoRequestBuilderRequestsMetadata, type InfoRequestBuilder } from './info/index.js';
// @ts-ignore
import { MemberRequestBuilderNavigationMetadata, type MemberRequestBuilder } from './member/index.js';
// @ts-ignore
import { MemberlistRequestBuilderRequestsMetadata, type MemberlistRequestBuilder } from './memberlist/index.js';
// @ts-ignore
import { SetadminRequestBuilderRequestsMetadata, type SetadminRequestBuilder } from './setadmin/index.js';
// @ts-ignore
import { TeamdetailRequestBuilderRequestsMetadata, type TeamdetailRequestBuilder } from './teamdetail/index.js';
// @ts-ignore
import { TeamitemRequestBuilderRequestsMetadata, type TeamitemRequestBuilder } from './teamitem/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/team/{teamId}
 */
export interface WithTeamItemRequestBuilder extends BaseRequestBuilder<WithTeamItemRequestBuilder> {
    /**
     * The adminlist property
     */
    get adminlist(): AdminlistRequestBuilder;
    /**
     * The config property
     */
    get config(): ConfigRequestBuilder;
    /**
     * The create property
     */
    get create(): CreateRequestBuilder;
    /**
     * The deletePath property
     */
    get deletePath(): DeleteRequestBuilder;
    /**
     * The info property
     */
    get info(): InfoRequestBuilder;
    /**
     * The member property
     */
    get member(): MemberRequestBuilder;
    /**
     * The memberlist property
     */
    get memberlist(): MemberlistRequestBuilder;
    /**
     * The setadmin property
     */
    get setadmin(): SetadminRequestBuilder;
    /**
     * The teamdetail property
     */
    get teamdetail(): TeamdetailRequestBuilder;
    /**
     * The teamitem property
     */
    get teamitem(): TeamitemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithTeamItemRequestBuilderUriTemplate = "{+baseurl}/api/team/{teamId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithTeamItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithTeamItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    adminlist: {
        requestsMetadata: AdminlistRequestBuilderRequestsMetadata,
    },
    config: {
        navigationMetadata: ConfigRequestBuilderNavigationMetadata,
    },
    create: {
        requestsMetadata: CreateRequestBuilderRequestsMetadata,
    },
    deletePath: {
        requestsMetadata: DeleteRequestBuilderRequestsMetadata,
    },
    info: {
        requestsMetadata: InfoRequestBuilderRequestsMetadata,
    },
    member: {
        navigationMetadata: MemberRequestBuilderNavigationMetadata,
    },
    memberlist: {
        requestsMetadata: MemberlistRequestBuilderRequestsMetadata,
    },
    setadmin: {
        requestsMetadata: SetadminRequestBuilderRequestsMetadata,
    },
    teamdetail: {
        requestsMetadata: TeamdetailRequestBuilderRequestsMetadata,
    },
    teamitem: {
        requestsMetadata: TeamitemRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
