/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMaomiAITeamSharedQueriesResponsesTeamSimpleResponseFromDiscriminatorValue, type MaomiAITeamSharedQueriesResponsesTeamSimpleResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/team/{-id}/teamitem
 */
export interface TeamitemRequestBuilder extends BaseRequestBuilder<TeamitemRequestBuilder> {
    /**
     * 查询团队简要信息.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MaomiAITeamSharedQueriesResponsesTeamSimpleResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MaomiAITeamSharedQueriesResponsesTeamSimpleResponse | undefined>;
    /**
     * 查询团队简要信息.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TeamitemRequestBuilderUriTemplate = "{+baseurl}/api/team/{%2Did}/teamitem";
/**
 * Metadata for all the requests in the request builder.
 */
export const TeamitemRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: TeamitemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createMaomiAITeamSharedQueriesResponsesTeamSimpleResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
