/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ClearRequestBuilderRequestsMetadata, type ClearRequestBuilder } from './clear/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/{teamId}/wiki
 */
export interface WikiRequestBuilder extends BaseRequestBuilder<WikiRequestBuilder> {
    /**
     * The clear property
     */
    get clear(): ClearRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WikiRequestBuilderUriTemplate = "{+baseurl}/api/wiki/{teamId}/wiki";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WikiRequestBuilderNavigationMetadata: Record<Exclude<keyof WikiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    clear: {
        requestsMetadata: ClearRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
