/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue, createMaomiAIStoreCommandsResponseComplateFileCommandResponseFromDiscriminatorValue, serializeMaomiAIDocumentSharedCommandsComplateUploadWikiDocumentCommand, serializeMaomiAIStoreCommandsResponseComplateFileCommandResponse, type MaomiAIDocumentSharedCommandsComplateUploadWikiDocumentCommand, type MaomiAIInfraModelsBusinessExceptionResponse, type MaomiAIStoreCommandsResponseComplateFileCommandResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/{teamId}/{wikiId}/complate_upload
 */
export interface Complate_uploadRequestBuilder extends BaseRequestBuilder<Complate_uploadRequestBuilder> {
    /**
     * 完成文档上传.
     * @param body 结束上传文件.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MaomiAIStoreCommandsResponseComplateFileCommandResponse>}
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 400 status code
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 401 status code
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 403 status code
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 409 status code
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 500 status code
     */
     post(body: MaomiAIDocumentSharedCommandsComplateUploadWikiDocumentCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MaomiAIStoreCommandsResponseComplateFileCommandResponse | undefined>;
    /**
     * 完成文档上传.
     * @param body 结束上传文件.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MaomiAIDocumentSharedCommandsComplateUploadWikiDocumentCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Complate_uploadRequestBuilderUriTemplate = "{+baseurl}/api/wiki/{teamId}/{wikiId}/complate_upload";
/**
 * Metadata for all the requests in the request builder.
 */
export const Complate_uploadRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Complate_uploadRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createMaomiAIStoreCommandsResponseComplateFileCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMaomiAIDocumentSharedCommandsComplateUploadWikiDocumentCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
