/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessExceptionResponseFromDiscriminatorValue, createComplateFileCommandResponseFromDiscriminatorValue, serializeComplateFileCommandResponse, serializeComplateFileUploadCommand, type BusinessExceptionResponse, type ComplateFileCommandResponse, type ComplateFileUploadCommand } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/store/complate_url
 */
export interface Complate_urlRequestBuilder extends BaseRequestBuilder<Complate_urlRequestBuilder> {
    /**
     * 完成文件上传，私有和公有文件都可以使用.
     * @param body 结束上传文件.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ComplateFileCommandResponse>}
     * @throws {BusinessExceptionResponse} error when the service returns a 400 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 401 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 403 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 409 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 500 status code
     */
     post(body: ComplateFileUploadCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ComplateFileCommandResponse | undefined>;
    /**
     * 完成文件上传，私有和公有文件都可以使用.
     * @param body 结束上传文件.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ComplateFileUploadCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Complate_urlRequestBuilderUriTemplate = "{+baseurl}/api/store/complate_url";
/**
 * Metadata for all the requests in the request builder.
 */
export const Complate_urlRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Complate_urlRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createComplateFileCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeComplateFileUploadCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
