/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { Check_existRequestBuilderRequestsMetadata, type Check_existRequestBuilder } from './check_exist/index.js';
// @ts-ignore
import { Complate_urlRequestBuilderRequestsMetadata, type Complate_urlRequestBuilder } from './complate_url/index.js';
// @ts-ignore
import { Pre_upload_imageRequestBuilderRequestsMetadata, type Pre_upload_imageRequestBuilder } from './pre_upload_image/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/store
 */
export interface StoreRequestBuilder extends BaseRequestBuilder<StoreRequestBuilder> {
    /**
     * The check_exist property
     */
    get check_exist(): Check_existRequestBuilder;
    /**
     * The complate_url property
     */
    get complate_url(): Complate_urlRequestBuilder;
    /**
     * The pre_upload_image property
     */
    get pre_upload_image(): Pre_upload_imageRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const StoreRequestBuilderUriTemplate = "{+baseurl}/api/store";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const StoreRequestBuilderNavigationMetadata: Record<Exclude<keyof StoreRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    check_exist: {
        requestsMetadata: Check_existRequestBuilderRequestsMetadata,
    },
    complate_url: {
        requestsMetadata: Complate_urlRequestBuilderRequestsMetadata,
    },
    pre_upload_image: {
        requestsMetadata: Pre_upload_imageRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
