/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { Check_nameRequestBuilderRequestsMetadata, type Check_nameRequestBuilder } from './check_name/index.js';
// @ts-ignore
import { type WithTeamItemRequestBuilder, WithTeamItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { Joined_listRequestBuilderRequestsMetadata, type Joined_listRequestBuilder } from './joined_list/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/team
 */
export interface TeamRequestBuilder extends BaseRequestBuilder<TeamRequestBuilder> {
    /**
     * The check_name property
     */
    get check_name(): Check_nameRequestBuilder;
    /**
     * The joined_list property
     */
    get joined_list(): Joined_listRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.team.item collection
     * @param teamId 团队ID.
     * @returns {WithTeamItemRequestBuilder}
     */
     byTeamId(teamId: Guid) : WithTeamItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TeamRequestBuilderUriTemplate = "{+baseurl}/api/team";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TeamRequestBuilderNavigationMetadata: Record<Exclude<keyof TeamRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTeamId: {
        navigationMetadata: WithTeamItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["teamId"],
    },
    check_name: {
        requestsMetadata: Check_nameRequestBuilderRequestsMetadata,
    },
    joined_list: {
        requestsMetadata: Joined_listRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
