/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMaomiAIPublicQueriesResponseQueryServerInfoResponseFromDiscriminatorValue, type MaomiAIPublicQueriesResponseQueryServerInfoResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/public/serverinfo
 */
export interface ServerinfoRequestBuilder extends BaseRequestBuilder<ServerinfoRequestBuilder> {
    /**
     * 获取服务器信息.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MaomiAIPublicQueriesResponseQueryServerInfoResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MaomiAIPublicQueriesResponseQueryServerInfoResponse | undefined>;
    /**
     * 获取服务器信息.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ServerinfoRequestBuilderUriTemplate = "{+baseurl}/api/public/serverinfo";
/**
 * Metadata for all the requests in the request builder.
 */
export const ServerinfoRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ServerinfoRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createMaomiAIPublicQueriesResponseQueryServerInfoResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
