/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMaomiAIUserSharedCommandsResponsesLoginCommandResponseFromDiscriminatorValue, serializeMaomiAIUserSharedCommandsRefreshTokenCommand, serializeMaomiAIUserSharedCommandsResponsesLoginCommandResponse, type MaomiAIUserSharedCommandsRefreshTokenCommand, type MaomiAIUserSharedCommandsResponsesLoginCommandResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/user/refresh_token
 */
export interface Refresh_tokenRequestBuilder extends BaseRequestBuilder<Refresh_tokenRequestBuilder> {
    /**
     * 刷新token.
     * @param body 刷新 token.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MaomiAIUserSharedCommandsResponsesLoginCommandResponse>}
     */
     post(body: MaomiAIUserSharedCommandsRefreshTokenCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MaomiAIUserSharedCommandsResponsesLoginCommandResponse | undefined>;
    /**
     * 刷新token.
     * @param body 刷新 token.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MaomiAIUserSharedCommandsRefreshTokenCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Refresh_tokenRequestBuilderUriTemplate = "{+baseurl}/api/user/refresh_token";
/**
 * Metadata for all the requests in the request builder.
 */
export const Refresh_tokenRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Refresh_tokenRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createMaomiAIUserSharedCommandsResponsesLoginCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMaomiAIUserSharedCommandsRefreshTokenCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
