/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessExceptionResponseFromDiscriminatorValue, createQueryWikiDetailInfoResponseFromDiscriminatorValue, serializeQueryWikiDetailInfoCommand, serializeQueryWikiDetailInfoResponse, type BusinessExceptionResponse, type QueryWikiDetailInfoCommand, type QueryWikiDetailInfoResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/{teamId}/detail
 */
export interface DetailRequestBuilder extends BaseRequestBuilder<DetailRequestBuilder> {
    /**
     * 知识库详细信息.
     * @param body 查询知识库详细信息.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryWikiDetailInfoResponse>}
     * @throws {BusinessExceptionResponse} error when the service returns a 400 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 401 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 403 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 409 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 500 status code
     */
     post(body: QueryWikiDetailInfoCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryWikiDetailInfoResponse | undefined>;
    /**
     * 知识库详细信息.
     * @param body 查询知识库详细信息.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryWikiDetailInfoCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DetailRequestBuilderUriTemplate = "{+baseurl}/api/wiki/{teamId}/detail";
/**
 * Metadata for all the requests in the request builder.
 */
export const DetailRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: DetailRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryWikiDetailInfoResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryWikiDetailInfoCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
