/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMaomiAIInfraModelsEmptyCommandResponseFromDiscriminatorValue, serializeMaomiAIInfraModelsEmptyCommandResponse, serializeMaomiAIUserSharedCommandsUploadtUserAvatarCommand, type MaomiAIInfraModelsEmptyCommandResponse, type MaomiAIUserSharedCommandsUploadtUserAvatarCommand } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/user/uploadavatar
 */
export interface UploadavatarRequestBuilder extends BaseRequestBuilder<UploadavatarRequestBuilder> {
    /**
     * 结束上传头像.
     * @param body 上传用户头像.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MaomiAIInfraModelsEmptyCommandResponse>}
     */
     post(body: MaomiAIUserSharedCommandsUploadtUserAvatarCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MaomiAIInfraModelsEmptyCommandResponse | undefined>;
    /**
     * 结束上传头像.
     * @param body 上传用户头像.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MaomiAIUserSharedCommandsUploadtUserAvatarCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const UploadavatarRequestBuilderUriTemplate = "{+baseurl}/api/user/uploadavatar";
/**
 * Metadata for all the requests in the request builder.
 */
export const UploadavatarRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: UploadavatarRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createMaomiAIInfraModelsEmptyCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMaomiAIUserSharedCommandsUploadtUserAvatarCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
