/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CreateRequestBuilderRequestsMetadata, type CreateRequestBuilder } from './create/index.js';
// @ts-ignore
import { SetdefaultRequestBuilderRequestsMetadata, type SetdefaultRequestBuilder } from './setdefault/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/aimodel/{teamId}/aimodel
 */
export interface AimodelRequestBuilder extends BaseRequestBuilder<AimodelRequestBuilder> {
    /**
     * The create property
     */
    get create(): CreateRequestBuilder;
    /**
     * The setdefault property
     */
    get setdefault(): SetdefaultRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AimodelRequestBuilderUriTemplate = "{+baseurl}/api/aimodel/{teamId}/aimodel";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AimodelRequestBuilderNavigationMetadata: Record<Exclude<keyof AimodelRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    create: {
        requestsMetadata: CreateRequestBuilderRequestsMetadata,
    },
    setdefault: {
        requestsMetadata: SetdefaultRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
