/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMaomiAIInfraModelsEmptyCommandResponseFromDiscriminatorValue, serializeMaomiAIInfraModelsEmptyCommandResponse, serializeMaomiAITeamSharedCommandsRootSetTeamAdminCommand, type MaomiAIInfraModelsEmptyCommandResponse, type MaomiAITeamSharedCommandsRootSetTeamAdminCommand } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/team/setadmin
 */
export interface SetadminRequestBuilder extends BaseRequestBuilder<SetadminRequestBuilder> {
    /**
     * 设置团队管理员.
     * @param body 设置成员为管理员.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MaomiAIInfraModelsEmptyCommandResponse>}
     */
     post(body: MaomiAITeamSharedCommandsRootSetTeamAdminCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MaomiAIInfraModelsEmptyCommandResponse | undefined>;
    /**
     * 设置团队管理员.
     * @param body 设置成员为管理员.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MaomiAITeamSharedCommandsRootSetTeamAdminCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SetadminRequestBuilderUriTemplate = "{+baseurl}/api/team/setadmin";
/**
 * Metadata for all the requests in the request builder.
 */
export const SetadminRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: SetadminRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createMaomiAIInfraModelsEmptyCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMaomiAITeamSharedCommandsRootSetTeamAdminCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
