/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessExceptionResponseFromDiscriminatorValue, createPreUploadOpenApiFileCommandResponseFromDiscriminatorValue, serializePreUploadOpenApiFileCommand, serializePreUploadOpenApiFileCommandResponse, type BusinessExceptionResponse, type PreUploadOpenApiFileCommand, type PreUploadOpenApiFileCommandResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/plugin/{teamId}/pre_upload_openapi
 */
export interface Pre_upload_openapiRequestBuilder extends BaseRequestBuilder<Pre_upload_openapiRequestBuilder> {
    /**
     * 预上传 openapi 文件.
     * @param body 预上传 openapi 文件，支持 json、yaml.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PreUploadOpenApiFileCommandResponse>}
     * @throws {BusinessExceptionResponse} error when the service returns a 400 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 401 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 403 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 409 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 500 status code
     */
     post(body: PreUploadOpenApiFileCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PreUploadOpenApiFileCommandResponse | undefined>;
    /**
     * 预上传 openapi 文件.
     * @param body 预上传 openapi 文件，支持 json、yaml.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: PreUploadOpenApiFileCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Pre_upload_openapiRequestBuilderUriTemplate = "{+baseurl}/api/plugin/{teamId}/pre_upload_openapi";
/**
 * Metadata for all the requests in the request builder.
 */
export const Pre_upload_openapiRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Pre_upload_openapiRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPreUploadOpenApiFileCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializePreUploadOpenApiFileCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
