/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessExceptionResponseFromDiscriminatorValue, createQueryDefaultAiModelListResponseFromDiscriminatorValue, serializeQueryDefaultAiModelListCommand, serializeQueryDefaultAiModelListResponse, type BusinessExceptionResponse, type QueryDefaultAiModelListCommand, type QueryDefaultAiModelListResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/aimodel/{teamId}/default_aimodel
 */
export interface Default_aimodelRequestBuilder extends BaseRequestBuilder<Default_aimodelRequestBuilder> {
    /**
     * 查询供应商模型默认列表，获取在某个功能需求下默认使用的模型.
     * @param body 查询供应商模型默认列表，获取在某个功能需求下默认使用的模型.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryDefaultAiModelListResponse>}
     * @throws {BusinessExceptionResponse} error when the service returns a 400 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 401 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 403 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 409 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 500 status code
     */
     post(body: QueryDefaultAiModelListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryDefaultAiModelListResponse | undefined>;
    /**
     * 查询供应商模型默认列表，获取在某个功能需求下默认使用的模型.
     * @param body 查询供应商模型默认列表，获取在某个功能需求下默认使用的模型.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryDefaultAiModelListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Default_aimodelRequestBuilderUriTemplate = "{+baseurl}/api/aimodel/{teamId}/default_aimodel";
/**
 * Metadata for all the requests in the request builder.
 */
export const Default_aimodelRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Default_aimodelRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryDefaultAiModelListResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryDefaultAiModelListCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
