/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ChecknameRequestBuilderRequestsMetadata, type ChecknameRequestBuilder } from './checkname/index.js';
// @ts-ignore
import { InfoRequestBuilderRequestsMetadata, type InfoRequestBuilder } from './info/index.js';
// @ts-ignore
import { LoginRequestBuilderRequestsMetadata, type LoginRequestBuilder } from './login/index.js';
// @ts-ignore
import { Refresh_tokenRequestBuilderRequestsMetadata, type Refresh_tokenRequestBuilder } from './refresh_token/index.js';
// @ts-ignore
import { RegisterRequestBuilderRequestsMetadata, type RegisterRequestBuilder } from './register/index.js';
// @ts-ignore
import { ResetpasswordRequestBuilderRequestsMetadata, type ResetpasswordRequestBuilder } from './resetpassword/index.js';
// @ts-ignore
import { type UploadavatarRequestBuilder, UploadavatarRequestBuilderRequestsMetadata } from './uploadavatar/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/user
 */
export interface UserRequestBuilder extends BaseRequestBuilder<UserRequestBuilder> {
    /**
     * The checkname property
     */
    get checkname(): ChecknameRequestBuilder;
    /**
     * The info property
     */
    get info(): InfoRequestBuilder;
    /**
     * The login property
     */
    get login(): LoginRequestBuilder;
    /**
     * The refresh_token property
     */
    get refresh_token(): Refresh_tokenRequestBuilder;
    /**
     * The register property
     */
    get register(): RegisterRequestBuilder;
    /**
     * The resetpassword property
     */
    get resetpassword(): ResetpasswordRequestBuilder;
    /**
     * The uploadavatar property
     */
    get uploadavatar(): UploadavatarRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const UserRequestBuilderUriTemplate = "{+baseurl}/api/user";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const UserRequestBuilderNavigationMetadata: Record<Exclude<keyof UserRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    checkname: {
        requestsMetadata: ChecknameRequestBuilderRequestsMetadata,
    },
    info: {
        requestsMetadata: InfoRequestBuilderRequestsMetadata,
    },
    login: {
        requestsMetadata: LoginRequestBuilderRequestsMetadata,
    },
    refresh_token: {
        requestsMetadata: Refresh_tokenRequestBuilderRequestsMetadata,
    },
    register: {
        requestsMetadata: RegisterRequestBuilderRequestsMetadata,
    },
    resetpassword: {
        requestsMetadata: ResetpasswordRequestBuilderRequestsMetadata,
    },
    uploadavatar: {
        requestsMetadata: UploadavatarRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
