/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue, createMaomiAIInfraModelsPagedResultOfTeamMemberResponseFromDiscriminatorValue, serializeMaomiAIInfraModelsPagedResultOfTeamMemberResponse, serializeMaomiAITeamSharedQueriesAdminQueryTeamMemberListCommand, type MaomiAIInfraModelsBusinessExceptionResponse, type MaomiAIInfraModelsPagedResultOfTeamMemberResponse, type MaomiAITeamSharedQueriesAdminQueryTeamMemberListCommand } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/team/{-id}/memberlist
 */
export interface MemberlistRequestBuilder extends BaseRequestBuilder<MemberlistRequestBuilder> {
    /**
     * 团队成员列表.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MaomiAIInfraModelsPagedResultOfTeamMemberResponse>}
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 400 status code
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 401 status code
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 403 status code
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 409 status code
     * @throws {MaomiAIInfraModelsBusinessExceptionResponse} error when the service returns a 500 status code
     */
     post(body: MaomiAITeamSharedQueriesAdminQueryTeamMemberListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MaomiAIInfraModelsPagedResultOfTeamMemberResponse | undefined>;
    /**
     * 团队成员列表.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MaomiAITeamSharedQueriesAdminQueryTeamMemberListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const MemberlistRequestBuilderUriTemplate = "{+baseurl}/api/team/{%2Did}/memberlist";
/**
 * Metadata for all the requests in the request builder.
 */
export const MemberlistRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: MemberlistRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createMaomiAIInfraModelsBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createMaomiAIInfraModelsPagedResultOfTeamMemberResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMaomiAITeamSharedQueriesAdminQueryTeamMemberListCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
