/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ConfigRequestBuilderRequestsMetadata, type ConfigRequestBuilder } from './config/index.js';
// @ts-ignore
import { Default_modelRequestBuilderRequestsMetadata, type Default_modelRequestBuilder } from './default_model/index.js';
// @ts-ignore
import { type Upload_avatarRequestBuilder, Upload_avatarRequestBuilderRequestsMetadata } from './upload_avatar/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/{temaId}/settings
 */
export interface SettingsRequestBuilder extends BaseRequestBuilder<SettingsRequestBuilder> {
    /**
     * The config property
     */
    get config(): ConfigRequestBuilder;
    /**
     * The default_model property
     */
    get default_model(): Default_modelRequestBuilder;
    /**
     * The upload_avatar property
     */
    get upload_avatar(): Upload_avatarRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SettingsRequestBuilderUriTemplate = "{+baseurl}/api/wiki/{temaId}/settings";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SettingsRequestBuilderNavigationMetadata: Record<Exclude<keyof SettingsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    config: {
        requestsMetadata: ConfigRequestBuilderRequestsMetadata,
    },
    default_model: {
        requestsMetadata: Default_modelRequestBuilderRequestsMetadata,
    },
    upload_avatar: {
        requestsMetadata: Upload_avatarRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
