/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { SearchRequestBuilderRequestsMetadata, type SearchRequestBuilder } from './search/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/{team-id}/document
 */
export interface DocumentRequestBuilder extends BaseRequestBuilder<DocumentRequestBuilder> {
    /**
     * The search property
     */
    get search(): SearchRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const DocumentRequestBuilderUriTemplate = "{+baseurl}/api/wiki/{team%2Did}/document";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DocumentRequestBuilderNavigationMetadata: Record<Exclude<keyof DocumentRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    search: {
        requestsMetadata: SearchRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
