/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessExceptionResponseFromDiscriminatorValue, createQueryWikiDocumentTaskListCommandResponseFromDiscriminatorValue, serializeQueryWikiDocumentTaskListCommand, serializeQueryWikiDocumentTaskListCommandResponse, type BusinessExceptionResponse, type QueryWikiDocumentTaskListCommand, type QueryWikiDocumentTaskListCommandResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/{teamId}/{wikiId}/document_tasks
 */
export interface Document_tasksRequestBuilder extends BaseRequestBuilder<Document_tasksRequestBuilder> {
    /**
     * 获取文档任务列表.
     * @param body 查询文档任务列表.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryWikiDocumentTaskListCommandResponse[]>}
     * @throws {BusinessExceptionResponse} error when the service returns a 400 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 401 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 403 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 409 status code
     * @throws {BusinessExceptionResponse} error when the service returns a 500 status code
     */
     post(body: QueryWikiDocumentTaskListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryWikiDocumentTaskListCommandResponse[] | undefined>;
    /**
     * 获取文档任务列表.
     * @param body 查询文档任务列表.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryWikiDocumentTaskListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Document_tasksRequestBuilderUriTemplate = "{+baseurl}/api/wiki/{teamId}/{wikiId}/document_tasks";
/**
 * Metadata for all the requests in the request builder.
 */
export const Document_tasksRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Document_tasksRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessExceptionResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createQueryWikiDocumentTaskListCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryWikiDocumentTaskListCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
