/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { Complate_uploadRequestBuilderRequestsMetadata, type Complate_uploadRequestBuilder } from './complate_upload/index.js';
// @ts-ignore
import { DeleteRequestBuilderRequestsMetadata, type DeleteRequestBuilder } from './delete/index.js';
// @ts-ignore
import { DetailRequestBuilderRequestsMetadata, type DetailRequestBuilder } from './detail/index.js';
// @ts-ignore
import { DocumentsRequestBuilderRequestsMetadata, type DocumentsRequestBuilder } from './documents/index.js';
// @ts-ignore
import { PreuploadRequestBuilderRequestsMetadata, type PreuploadRequestBuilder } from './preupload/index.js';
// @ts-ignore
import { SimpleRequestBuilderRequestsMetadata, type SimpleRequestBuilder } from './simple/index.js';
// @ts-ignore
import { type UpdateRequestBuilder, UpdateRequestBuilderRequestsMetadata } from './update/index.js';
// @ts-ignore
import { type Upload_avatarRequestBuilder, Upload_avatarRequestBuilderRequestsMetadata } from './upload_avatar/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/{teamId}/{wikiId}
 */
export interface WithWikiItemRequestBuilder extends BaseRequestBuilder<WithWikiItemRequestBuilder> {
    /**
     * The complate_upload property
     */
    get complate_upload(): Complate_uploadRequestBuilder;
    /**
     * The deletePath property
     */
    get deletePath(): DeleteRequestBuilder;
    /**
     * The detail property
     */
    get detail(): DetailRequestBuilder;
    /**
     * The documents property
     */
    get documents(): DocumentsRequestBuilder;
    /**
     * The preupload property
     */
    get preupload(): PreuploadRequestBuilder;
    /**
     * The simple property
     */
    get simple(): SimpleRequestBuilder;
    /**
     * The update property
     */
    get update(): UpdateRequestBuilder;
    /**
     * The upload_avatar property
     */
    get upload_avatar(): Upload_avatarRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithWikiItemRequestBuilderUriTemplate = "{+baseurl}/api/wiki/{teamId}/{wikiId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithWikiItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithWikiItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    complate_upload: {
        requestsMetadata: Complate_uploadRequestBuilderRequestsMetadata,
    },
    deletePath: {
        requestsMetadata: DeleteRequestBuilderRequestsMetadata,
    },
    detail: {
        requestsMetadata: DetailRequestBuilderRequestsMetadata,
    },
    documents: {
        requestsMetadata: DocumentsRequestBuilderRequestsMetadata,
    },
    preupload: {
        requestsMetadata: PreuploadRequestBuilderRequestsMetadata,
    },
    simple: {
        requestsMetadata: SimpleRequestBuilderRequestsMetadata,
    },
    update: {
        requestsMetadata: UpdateRequestBuilderRequestsMetadata,
    },
    upload_avatar: {
        requestsMetadata: Upload_avatarRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
