/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithTeamItemRequestBuilder, WithTeamItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/aimodel
 */
export interface AimodelRequestBuilder extends BaseRequestBuilder<AimodelRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.aimodel.item collection
     * @param teamId 团队 id.
     * @returns {WithTeamItemRequestBuilder}
     */
     byTeamId(teamId: Guid) : WithTeamItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AimodelRequestBuilderUriTemplate = "{+baseurl}/api/aimodel";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AimodelRequestBuilderNavigationMetadata: Record<Exclude<keyof AimodelRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTeamId: {
        navigationMetadata: WithTeamItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["teamId"],
    },
};
/* tslint:enable */
/* eslint-enable */
